spring:
  profiles:
    active: local


---
spring:
  profiles:
    include: oauth
  datasource:
    url: jdbc:h2:~/data/devactivity
    username: "sa"
    password: ""

  jpa:
    hibernate:
      ddl-auto: create
