spring:
  profiles:
    active: local


---
spring:
  profiles:
    include: oauth
  datasource:
    url: jdbc:h2:~/data/devactivity
    username: "sa"
    password: ""
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      show_sql: true
      hibernate:
        format_sql: true
        show_sql: true
#        generate_statistics: true
#        jdbc:
#          batch_size: 1000
#        order_inserts: true
  level:
    org:
      hibernate:
        SQL: debug
        type: trace


  mvc:
    hiddenmethod:
      filter:
        enabled: true
