spring:
  profiles:
    active: local


---
spring:
  profiles:
    include: oauth
  datasource:
    url: jdbc:h2:~/data/devactivity
    username: "sa"
    password: ""
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false


  jpa:
    hibernate:
      ddl-auto: create
